name: build-linux
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: install build tools
      run: |
        apt update -y
        apt install -y cmake make g++-10
    - name: run cmake
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -S . -B bin
    - name: run make
      run: |
        make -j 2 -C bin

