name: clang-format check

on: push

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'

    steps:
    - uses: actions/checkout@v2
    - name: clang-format check
      uses: jidicula/clang-format-action@v3.4.0
      with:
        clang-format-version: '12'
        check-path: ${{ matrix.path }}
