name: cppcheck
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [unix64, win64, unix32, win32]
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          check_library:
          skip_preprocessor:
          enable: warning,missingInclude
          exclude_check:
          inconclusive: enable
          inline_suppression:
          force_language: c++
          force: 
          max_ctu_depth: 4
          platform: ${{ matrix.platform }}
          std: c++20
          output_file:
          other_options:

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
