name: spellcheck

on: push

jobs:
  spellcheck:
    name: typo ci
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - name: spellcheck
      uses: typoci/spellcheck-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
